services:
  php-fpm:
    build:
      context: docker/php
    volumes:
      - '.:/var/www/html'
      - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf'
    restart: always
    depends_on:
      - php-fpm
      - db

  db:
    image: postgres:14.10
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_CONNECTION=${DB_CONNECTION}
      - POSTGRES_PORT=${DB_PORT}
    ports:
      - "5432:5432"
